"""create recovery token table

Revision ID: b8e3655e3fd7
Revises: 7a2e25eb55ec
Create Date: 2026-09-03 18:37:16.336380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e3655e3fd7'
down_revision: Union[str, Sequence[str], None] = '7a2e25eb55ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_tokens'))
    )
    op.create_index(op.f('ix_recovery_tokens_token_hash'), 'recovery_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_recovery_tokens_user_id'), 'recovery_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_tokens_user_id'), table_name='recovery_tokens')
    op.drop_index(op.f('ix_recovery_tokens_token_hash'), table_name='recovery_tokens')
    op.drop_table('recovery_tokens')
    # ### end Alembic commands ###
