"""add nullable for description

Revision ID: 7a2e25eb55ec
Revises: f9ede0964626
Create Date: 2026-08-11 21:23:26.448095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2e25eb55ec'
down_revision: Union[str, Sequence[str], None] = 'f9ede0964626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=450),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'description',
               existing_type=sa.String(length=450),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
